### ISSUE TITLE
Python 3: delete-docker-containers broken

### ISSUE THREAD

**Issue by pfuntner** [pfuntner/toys#60]
I'm finding more scripts that aren't working with Python 3:

```
$ delete_docker_containers
CONTAINER ID        IMAGE               COMMAND                  CREATED              STATUS              PORTS               NAMES
47d0d5ff12b4        cc0abc535e36        "bash -c 'sleep 3153…"   About a minute ago   Created                                 alpine-latest-20200103094308152624
1f6474c87756        549b9b86cb8d        "bash -c 'sleep 3153…"   About a minute ago   Up About a minute                       ubuntu-18.04-20200103094257448886
0bc2b9f607d6        c6a43cd4801e        "bash -c 'sleep 3153…"   About a minute ago   Up About a minute                       ubuntu-16.04-20200103094256287931
32f5a41ddd39        f6c68e2ad82a        "bash -c 'sleep 3153…"   About a minute ago   Up About a minute                       debian-9-20200103094255098109
59349c9de889        5d7d9c6338e8        "bash -c 'sleep 3153…"   About a minute ago   Up About a minute                       debian-8-20200103094253913629
44c331f95bde        5e35e350aded        "bash -c 'sleep 3153…"   About a minute ago   Up About a minute                       centos-7-20200103094252741353
9db2ea3fa9d0        d0957ffdf8a2        "bash -c 'sleep 3153…"   About a minute ago   Up About a minute                       centos-6-20200103094251576296

Remove all containers? yes
47d0d5ff12b4
1f6474c87756
0bc2b9f607d6
32f5a41ddd39
59349c9de889
44c331f95bde
9db2ea3fa9d0
Traceback (most recent call last):
  File "/home/centos/bin/delete_docker_containers", line 39, in <module>
    (rc, stderr, stderr) = run(['docker', 'rm', '-f'] + [line.split()[0] for line in lines[1:]], capture=False)
  File "/home/centos/bin/delete_docker_containers", line 15, in run
    stdout = stdout.decode('utf-8')
AttributeError: 'NoneType' object has no attribute 'decode'
$
```

Switching back to Python 2 for now.

**Comment by pfuntner** [comment]
The script does abort but only after it's already deleted all the containers!  Oh well!
