### ISSUE TITLE
Python 3: gzcat broken

### ISSUE THREAD

**Issue by pfuntner** [pfuntner/toys#62]
I thought I had an alias for `gzcat` but I guess I had a script for it for some reason.  I tried to use it today but it failed after being changed for Python 3:

```
$ gzcat < foo.tgz  | docker load
Traceback (most recent call last):
  File "/home/centos/bin/gzcat", line 43, in <module>
    process()
  File "/home/centos/bin/gzcat", line 22, in process
    stringStream = io.StringIO(zippedStream.read())
  File "/usr/lib64/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
open /var/lib/docker/tmp/docker-import-038838411/repositories: no such file or directory
$
```

I could probably get this working by switching back to Python 2 and I imagine the Python 3 change isn't that complicated either.  Maybe I just need to open the file in binary mode.  But there is still a simple alternative of using `gzip -d` - I just need to be careful to specify the file as stdin so it doesn't try to replace the file with the uncompressed version.

**Comment by pfuntner** [comment]
Fixed in 6cde85a58d51849dc0413f3423b29511c815d340:

```
[centos@pfuntner1 bin master]$ gzip -d < ~/tmp/now.gz | md5sum
3e62853c85f1fad7cee1e582bfaddb76  -
[centos@pfuntner1 bin master]$ gzcat < ~/tmp/now.gz | md5sum
3e62853c85f1fad7cee1e582bfaddb76  -
[centos@pfuntner1 bin master]$
```
