### ISSUE TITLE
Python 3: wcsum broken!

### ISSUE THREAD

**Issue by pfuntner** [pfuntner/toys#67]
I could not get `wcsum` working for me this morning:

```
[centos@pfuntner1 5-permissions.yml]$ for file in $(ls -tr); do echo $file $(grep -i pid $file | wc); done
3387e551c03e215c9e0a41f2e9198c75664dea57 26 130 1099
99532b2ae573bcc799724b6d15169444b9f1d924 34 170 1489
.
.
.
4e78bfc77d7d3cb2743696d2465be3e35597222f 31 191 1647
b828925d65a8b80ad90cc638c9496e1bed447eb6 31 191 1647
[centos@pfuntner1 5-permissions.yml]$ for file in $(ls -tr); do echo $file $(grep -i pid $file | wcsum); done
Traceback (most recent call last):
  File "/home/centos/bin/wcsum", line 82, in <module>
    process()
  File "/home/centos/bin/wcsum", line 38, in process
    c = ''.join(map(chr, stream.read(1)))
io.UnsupportedOperation: read
3387e551c03e215c9e0a41f2e9198c75664dea57
Traceback (most recent call last):
  File "/home/centos/bin/wcsum", line 82, in <module>
    process()
  File "/home/centos/bin/wcsum", line 38, in process
    c = ''.join(map(chr, stream.read(1)))
io.UnsupportedOperation: read
99532b2ae573bcc799724b6d15169444b9f1d924
.
.
.

Traceback (most recent call last):
  File "/home/centos/bin/wcsum", line 82, in <module>
    process()
  File "/home/centos/bin/wcsum", line 38, in process
    c = ''.join(map(chr, stream.read(1)))
io.UnsupportedOperation: read
4e78bfc77d7d3cb2743696d2465be3e35597222f
Traceback (most recent call last):
  File "/home/centos/bin/wcsum", line 82, in <module>
    process()
  File "/home/centos/bin/wcsum", line 38, in process
    c = ''.join(map(chr, stream.read(1)))
io.UnsupportedOperation: read
b828925d65a8b80ad90cc638c9496e1bed447eb6
[centos@pfuntner1 5-permissions.yml]$
```

82bfb5352c8b1f20b96312b4fa9a8a7a2522d015: I temporarily patched this by reverting to Python 2 and reverted some of the code back to Python 2.

The files in question were versions of a Ansible role task file in a git repo extracted by `git-extract`.

**Comment by pfuntner** [comment]
Fixed with 2850d89 after playing with data in Python 3.
