### ISSUE TITLE
Python 3: SecureKeyValues broken!!

### ISSUE THREAD

**Issue by pfuntner** [pfuntner/toys#69]
The Python3 screwing continues:

```
$ SecureKeyValues.py -o test
Traceback (most recent call last):
  File "/home/jpfuntne/bin/SecureKeyValues.py", line 210, in <module>
    store = SecureKeyValues("test", "this is a test")
  File "/home/jpfuntne/bin/SecureKeyValues.py", line 95, in __init__
    self.key = base64.b64encode(hash.hexdigest())
  File "/usr/lib/python3.6/base64.py", line 58, in b64encode
    encoded = binascii.b2a_base64(s, newline=False)
TypeError: a bytes-like object is required, not 'str'
```

I'll revert it to Python 2 via 5c442df for now.

**Comment by pfuntner** [comment]
I pushed up the tentative changes as in the [issue-69](https://github.com/pfuntner/toys/tree/issue-69) branch, tried them on a VM with Python 3.10.12, and the changes worked fine there too.

**Comment by pfuntner** [comment]
Fixed by #125

**Comment by pfuntner** [comment]
My Windoze laptop also has Python 3.10.12 and the new changes work fine there.

**Comment by pfuntner** [comment]
My daily work machine (Python 3.11.0rc1) didn't work at first:

```
$ SecureKeyValues.py -o test
Traceback (most recent call last):
  File "/home/jpfuntne/bin/SecureKeyValues.py", line 14, in <module>
    import cryptography.fernet
  File "/usr/lib/python3/dist-packages/cryptography/fernet.py", line 16, in <module>
    from cryptography.hazmat.primitives import hashes, padding
  File "/usr/lib/python3/dist-packages/cryptography/hazmat/primitives/padding.py", line 11, in <module>
    from cryptography.hazmat.bindings._padding import lib
ModuleNotFoundError: No module named '_cffi_backend'
```

but when I looked more closely at the `ModuleNotFoundError` exception, that made me believe that it might work if I just installed the `cffi` package (whatever that it is!).  Installing it enabled the script to work.
