### ISSUE TITLE
table.py broken for --output xml

### ISSUE THREAD

**Issue by pfuntner** [pfuntner/toys#80]
I had trouble generating XML output:

```
$ df | table -i fixed --loose --headings -o xml
Traceback (most recent call last):
  File "/home/centos/.local/bin/table.py", line 951, in <module>
    args.output.write(sys.stdout, root, order)
  File "/home/centos/.local/bin/table.py", line 183, in write
    stream.write(ET.tostring(tree) + '\n')
TypeError: can't concat str to bytes
$
```

This could be a Python 2 thing - the script has been converted to work with Python 3.

**Comment by pfuntner** [comment]
Fixed by 8574f9f
