### ISSUE TITLE
some tools doesn't accept arbitrary characters

### ISSUE THREAD

**Issue by pfuntner** [pfuntner/toys#87]
I had this experience today with `br`:

```
[root@ip-172-31-60-146 ~]# journalctl -xe | br
Traceback (most recent call last):
  File "/root/repos/toys/bin/br", line 91, in <module>
    os.write(fd, add_crs(sys.stdin.read()).encode('utf-8'))
UnicodeEncodeError: 'utf-8' codec can't encode characters in position 40998-41000: surrogates not allowed
[root@ip-172-31-60-146 ~]#
```

I had a similar experience with `datascope` trying to diagnose the problem:
```
[root@ip-172-31-60-146 ~]# journalctl -xe | datascope | grep-cat 40998:41010
Traceback (most recent call last):
  File "/root/repos/toys/bin/datascope", line 28, in <module>
    print("%08d %06d %08d 0x%02x %3d 0%03o %s" % (chars, linenum, pos, ord(c), ord(c), ord(c), repr(c)))
UnicodeEncodeError: 'ascii' codec can't encode character '\xe2' in position 40: ordinal not in range(128)
2021-01-19 15:24:14,027 WARNING /root/repos/toys/bin/grep-cat:34 IntegerSelector(num=41010) does nothing to '<stdin>' since it only has 40783 lines
2021-01-19 15:24:14,027 WARNING /root/repos/toys/bin/grep-cat:34 IntegerSelector(num=40998) does nothing to '<stdin>' since it only has 40783 lines
2021-01-19 15:24:14,027 WARNING /root/repos/toys/bin/grep-cat:149 RangeSelector(IntegerSelector(num=40998)-IntegerSelector(num=41010)) has no effect since the starting selector did not match any lines in '<stdin>'
[root@ip-172-31-60-146 ~]# journalctl -xe | datascope | grep-cat 40998:41010
```

I used `head -cBYTES` and `tail -cBYTES` to narrow down the nastiness and then used `vi -R` to look at the data and I think I was able to find the evil character:
```
[root@ip-172-31-60-146 tmp]# journalctl -xe | grep 'Jan 19 14:59:38 ip-172-31-60-146.ec2.internal systemd-journal\[394\]: Runtime journal is using 8.0M'
Jan 19 14:59:38 ip-172-31-60-146.ec2.internal systemd-journal[394]: Runtime journal is using 8.0M (max allowed 91.8M, trying to leave 137.7M free of 902.0M available → current limit 91.8M).
[root@ip-172-31-60-146 tmp]# journalctl -xe | grep 'Jan 19 14:59:38 ip-172-31-60-146.ec2.internal systemd-journal\[394\]: Runtime journal is using 8.0M' | hex
00000000    J    a    n         1    9         1    4    :    5    9    :    3    8
           4a   61   6e   20   31   39   20   31   34   3a   35   39   3a   33   38   20
00000010    i    p    -    1    7    2    -    3    1    -    6    0    -    1    4    6
           69   70   2d   31   37   32   2d   33   31   2d   36   30   2d   31   34   36
00000020    .    e    c    2    .    i    n    t    e    r    n    a    l         s    y
           2e   65   63   32   2e   69   6e   74   65   72   6e   61   6c   20   73   79
00000030    s    t    e    m    d    -    j    o    u    r    n    a    l    [    3    9
           73   74   65   6d   64   2d   6a   6f   75   72   6e   61   6c   5b   33   39
00000040    4    ]    :         R    u    n    t    i    m    e         j    o    u    r
           34   5d   3a   20   52   75   6e   74   69   6d   65   20   6a   6f   75   72
00000050    n    a    l         i    s         u    s    i    n    g         8    .    0
           6e   61   6c   20   69   73   20   75   73   69   6e   67   20   38   2e   30
00000060    M         (    m    a    x         a    l    l    o    w    e    d         9
           4d   20   28   6d   61   78   20   61   6c   6c   6f   77   65   64   20   39
00000070    1    .    8    M    ,         t    r    y    i    n    g         t    o
           31   2e   38   4d   2c   20   74   72   79   69   6e   67   20   74   6f   20
00000080    l    e    a    v    e         1    3    7    .    7    M         f    r    e
           6c   65   61   76   65   20   31   33   37   2e   37   4d   20   66   72   65
00000090    e         o    f         9    0    2    .    0    M         a    v    a    i
           65   20   6f   66   20   39   30   32   2e   30   4d   20   61   76   61   69
000000a0    l    a    b    l    e      \xe2 \x86 \x92         c    u    r    r    e    n
           6c   61   62   6c   65   20   e2   86   92   20   63   75   72   72   65   6e
000000b0    t         l    i    m    i    t         9    1    .    8    M    )    .   \n
           74   20   6c   69   6d   69   74   20   39   31   2e   38   4d   29   2e   0a
[root@ip-172-31-60-146 tmp]#
```

**Comment by pfuntner** [comment]
`hex` is another one of my tools which looks like it has some Python3-esque improvements to get past this issue.

**Comment by pfuntner** [comment]
This could be a long process:

- [ ] br - cfdea14
- [ ] datascope
- [ ] hex

**Comment by pfuntner** [comment]
I don't know of anything else that's broken or anything I really expect to use binary data.  I'm going to close this and there can be new issues/commits for new problems.
