### ISSUE TITLE
grep-cat problem

### ISSUE THREAD

**Issue by pfuntner** [pfuntner/toys#91]
I ran into a scenario where `grep-cat` had a tummyache:

```
[ubuntu@pfuntner-ubuntu repos]$ ls | grep-cat '/kubernetes_install/+1:-1'
Usage: grep [OPTION]... PATTERNS [FILE]...
Try 'grep --help' for more information.
Traceback (most recent call last):
  File "/home/ubuntu/bin/grep-cat", line 297, in <module>
    process()
  File "/home/ubuntu/bin/grep-cat", line 210, in process
    print_line(file_name, pos, lines)
  File "/home/ubuntu/bin/grep-cat", line 157, in print_line
    print('{file_name}{pos}{space}{line}'.format(
BrokenPipeError: [Errno 32] Broken pipe
[ubuntu@pfuntner-ubuntu repos]$
```

I got it to work without reading from stdin:

```
[ubuntu@pfuntner-ubuntu repos]$ grep-cat '/kubernetes_install/+1:-1' <(ls)
/dev/fd/63: ansible-linux_security_module
/dev/fd/63: ansible-nginx_hardening
/dev/fd/63: ansible-nginx_install
/dev/fd/63: ansible-os_hardening
/dev/fd/63: ansible-osquery
/dev/fd/63: ansible-qualys-cloud-agent
/dev/fd/63: ansible-servertypes
/dev/fd/63: ansible-setup
/dev/fd/63: ansible-tomcat_hardening
/dev/fd/63: ansible-tomcat_install
/dev/fd/63: ansible-users
/dev/fd/63: automation-shared
/dev/fd/63: cis-cat-zipfiles
/dev/fd/63: cloud9-audit-tool
/dev/fd/63: cloud9-aws-lambda
/dev/fd/63: cloud9-ci-images
/dev/fd/63: cloud9-docs
/dev/fd/63: cloud9-docs-internal
/dev/fd/63: cloud9-jenkins-node-image
/dev/fd/63: cloud9-prehardened-images
/dev/fd/63: cloud9-sanity_tests
/dev/fd/63: cloud9-shared-libs
/dev/fd/63: cloud9-terraform
/dev/fd/63: cloud9-tools
/dev/fd/63: hardening-guides
/dev/fd/63: packer-examples
/dev/fd/63: reclone-cloud9-docs-internal.sh
/dev/fd/63: reclone-cloud9-docs.sh
[ubuntu@pfuntner-ubuntu repos]$
```

I think this is a case where I was expecting a filename but there isn't one.

**Comment by pfuntner** [comment]
I tried to recreate this but couldn't.  I don't remember seeing anything like this happen recently either.

**Comment by pfuntner** [comment]
I can't recreate this.
